name: Build xformers for torch 2.5.1+cu124

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CUDA Toolkit 12.4
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '12.4.0'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install PyTorch 2.5.1+cu124
        run: |
          pip install torch==2.5.1+cu124 torchvision --extra-index-url https://download.pytorch.org/whl/cu124

      - name: Install build dependencies
        run: |
          pip install ninja cmake
          pip install -r requirements.txt

      - name: Build wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: xformers-wheel-cu124
          path: dist/*.whl
